apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-data
  namespace: logging
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
